{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeflow-llm-training.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeflow-llm-training.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.hfToken }}
  hf-token: {{ .Values.secrets.hfToken | b64enc | quote }}
  {{- else }}
  hf-token: ""
  {{- end }}
  {{- if .Values.secrets.awsAccessKey }}
  aws-access-key: {{ .Values.secrets.awsAccessKey | b64enc | quote }}
  {{- else }}
  aws-access-key: ""
  {{- end }}
  {{- if .Values.secrets.awsSecretKey }}
  aws-secret-key: {{ .Values.secrets.awsSecretKey | b64enc | quote }}
  {{- else }}
  aws-secret-key: ""
  {{- end }}
  {{- if .Values.secrets.s3EndpointUrl }}
  s3-endpoint-url: {{ .Values.secrets.s3EndpointUrl | b64enc | quote }}
  {{- else }}
  s3-endpoint-url: ""
  {{- end }}
  {{- if .Values.secrets.wandbApiKey }}
  wandb-api-key: {{ .Values.secrets.wandbApiKey | b64enc | quote }}
  {{- else }}
  wandb-api-key: ""
  {{- end }}
{{- end }}
