apiVersion: v2
name: kubeflow-llm-training
description: Distributed LLM fine-tuning on Kubeflow using PyTorch FSDP and QLoRA
type: application
version: 0.2.1
appVersion: "1.0.1"
keywords:
  - kubeflow
  - pytorch
  - llm
  - fine-tuning
  - distributed-training
